"""Sample initial data for table initialization."""

INITIAL_DATA = [
    {
        'LAYOUT_ID': 'LAY001',
        'SELL_ID': 'SELL001',
        'PRODUCT_NAME': 'Coles Brand Milk 2L',
        'LOYALTY_GROUP': 'Core',
        'SEGMENT_1': 'High Value',
        'SEGMENT_2': 'Regular Shopper',
        'ORIGIN': 'AU',
        'CATEGORY_NAME': 'Dairy',
        'SUBCATEGORY_NAME': 'Milk',
        'ITEM_CLASS_NAME': 'Full Cream',
        'SUPPLIER': 'Coles Dairy',
        'BRAND': 'Coles',
        'PACK_SIZE': '2L',
        'SHELF_SPACE_CM': 12.5,
    },
    {
        'LAYOUT_ID': 'LAY002',
        'SELL_ID': 'SELL002',
        'PRODUCT_NAME': 'Woolworths Bread White',
        'LOYALTY_GROUP': 'Core',
        'SEGMENT_1': 'Regular Shopper',
        'SEGMENT_2': 'Family',
        'ORIGIN': 'AU',
        'CATEGORY_NAME': 'Bakery',
        'SUBCATEGORY_NAME': 'Bread',
        'ITEM_CLASS_NAME': 'White',
        'SUPPLIER': 'Woolworths Bakery',
        'BRAND': 'Woolworths',
        'PACK_SIZE': '650g',
        'SHELF_SPACE_CM': 15,
    },
    {
        'LAYOUT_ID': 'LAY003',
        'SELL_ID': 'SELL003',
        'PRODUCT_NAME': "Arnott's Tim Tams",
        'LOYALTY_GROUP': 'Premium',
        'SEGMENT_1': 'High Value',
        'SEGMENT_2': 'Regular Shopper',
        'ORIGIN': 'AU',
        'CATEGORY_NAME': 'Confectionery',
        'SUBCATEGORY_NAME': 'Biscuits',
        'ITEM_CLASS_NAME': 'Chocolate',
        'SUPPLIER': "Arnott's",
        'BRAND': "Arnott's",
        'PACK_SIZE': '200g',
        'SHELF_SPACE_CM': 8.5,
    },
    {
        'LAYOUT_ID': 'LAY004',
        'SELL_ID': 'SELL004',
        'PRODUCT_NAME': 'Vegemite 380g',
        'LOYALTY_GROUP': 'Core',
        'SEGMENT_1': 'Family',
        'SEGMENT_2': 'Regular Shopper',
        'ORIGIN': 'AU',
        'CATEGORY_NAME': 'Pantry',
        'SUBCATEGORY_NAME': 'Spreads',
        'ITEM_CLASS_NAME': 'Yeast Extract',
        'SUPPLIER': 'Bega',
        'BRAND': 'Vegemite',
        'PACK_SIZE': '380g',
        'SHELF_SPACE_CM': 7,
    },
    {
        'LAYOUT_ID': 'LAY005',
        'SELL_ID': 'SELL005',
        'PRODUCT_NAME': 'Kangaroo Steak',
        'LOYALTY_GROUP': 'Premium',
        'SEGMENT_1': 'Health Conscious',
        'SEGMENT_2': 'High Value',
        'ORIGIN': 'AU',
        'CATEGORY_NAME': 'Meat',
        'SUBCATEGORY_NAME': 'Game',
        'ITEM_CLASS_NAME': 'Steak',
        'SUPPLIER': 'Macro Meats',
        'BRAND': 'Macro',
        'PACK_SIZE': '500g',
        'SHELF_SPACE_CM': 18,
    },
    {
        'LAYOUT_ID': 'LAY006',
        'SELL_ID': 'SELL006',
        'PRODUCT_NAME': 'Tim Tam Slam Kit',
        'LOYALTY_GROUP': 'Premium',
        'SEGMENT_1': 'Impulse Buyer',
        'SEGMENT_2': 'High Value',
        'ORIGIN': 'AU',
        'CATEGORY_NAME': 'Confectionery',
        'SUBCATEGORY_NAME': 'Biscuits',
        'ITEM_CLASS_NAME': 'Gift Set',
        'SUPPLIER': "Arnott's",
        'BRAND': "Arnott's",
        'PACK_SIZE': '400g',
        'SHELF_SPACE_CM': 22,
    },
]
